# THIS PROGRAM WILL ACCEPT AN INTEGER AS INPUT RETURN THE FIBONACCI SEQUENCE UP TO THAT INTEGER
# IN FIBONACCI SEQUENCE THE FIRST TWO TERMS ARE 0 AND 1. ALL OTHER TERMS ARE OBTAINED BY ADDING THE PRECEDING TWO TERMS
N = int(input("ENTER THE NUMBER OF TERMS OF THE SEQUENCE (e.g. 6)  : "))

# FIRST TWO TERMS OF THE SEQUENCE ARE N1 AND N2
N1, N2 = 0, 1
COUNT = 0

# IF ELSE CONDITIONAL STATEMENTS ARE USED FOR CHECKING THE VALIDITY OF LAST TERM ENTERD
if N <= 0:
   print("\nPLEASE ENTER A POSITIVE INTEGER")
elif N == 1:
   print("\nFIBONACCI SEQUENCE IS : ")
   print(N1)
else:
   print("\nFIBONACCI SEQUENCE IS : \n")
   while COUNT < N:
       print(N1)
       NN = N1 + N2
       #UPDATE VALUES
       N1 = N2
       N2 = NN
       COUNT += 1



