# THIS PROGRAM WILL CHECK WHETHER THE ENTERED STRING IS PALINDROME OR NOT
# A PALINDROME IS A STRING THAT IS THE SAME READ FORWARD OR BACKWARD. E.G MALAYALAM
from run import *
STRING = input("\nENTER THE STRING YOU WANT TO CHECK WHETHER PALINDROME OR NOT :\n")
STRING = STRING.casefold() # MAKE THE ENTERED STRING SUITABLE FOR CASELESS COMPARISON
REVERSE_STRING = reversed(STRING) # REVERSE THE STRING
# CHECK WHETHER THE STRING IS EQUAL TO ITS REVERSE OR NO USING IF ELSE CONDITIONAL STATEMENTS
if list(STRING) == list(REVERSE_STRING):
   print("THE ENTERED STRING '", STRING, "' IS A PALINDROME.")
else:
   print("THE ENTERED STRING '", STRING, "' IS NOT A PALINDROME.")
run("PALINDROME_CHECKER.py")